"""Structured trace output for PredictRLM runs.

Captures iteration steps, predict() subcalls, token usage, and timings
in a machine-readable format for postmortem analysis and downstream systems.

.. warning:: Schema is experimental and may change in future versions.
"""

from __future__ import annotations

import json
import re
import time
from contextvars import ContextVar, Token
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field


class TokenUsage(BaseModel):
    """Aggregated token counts and cost for a set of LM calls.

    Cache hits are excluded from ``input_tokens``, ``output_tokens``, and
    ``cost`` (no new tokens were consumed and no new spend was incurred);
    they are surfaced separately via ``cache_hits`` for observability.
    """

    input_tokens: int = Field(default=0, description="Total input/prompt tokens")
    output_tokens: int = Field(default=0, description="Total output/completion tokens")
    cost: float = Field(default=0.0, description="Total billed cost in USD (excludes cache hits)")
    cache_hits: int = Field(
        default=0, description="Number of LM calls served from DSPy's cache"
    )

    def __iadd__(self, other: TokenUsage) -> TokenUsage:
        self.input_tokens += other.input_tokens
        self.output_tokens += other.output_tokens
        self.cost += other.cost
        self.cache_hits += other.cache_hits
        return self


class PredictCallDetail(BaseModel):
    """Per-call metrics for a single predict() invocation."""

    duration_ms: int = Field(description="Wall-clock duration in milliseconds")
    usage: TokenUsage = Field(
        default_factory=TokenUsage, description="Token usage for this call"
    )
    input: dict[str, Any] = Field(
        default_factory=dict, description="Input fields passed to the sub-LM"
    )
    output: dict[str, Any] = Field(
        default_factory=dict, description="Output fields returned by the sub-LM"
    )
    error: str | None = Field(
        default=None, description="Error message if the predict() call failed"
    )


class PredictCallGroup(BaseModel):
    """Grouped predict() subcalls sharing the same signature, instructions, and model.

    When multiple predict() calls are made in parallel (e.g. via asyncio.gather)
    with identical parameters, they are grouped to reduce trace bloat.
    """

    signature: str = Field(description="DSPy signature string")
    instructions: str | None = Field(
        default=None, description="Task instructions passed to the sub-LM"
    )
    model: str = Field(description="Model identifier used for these calls")
    total_usage: TokenUsage = Field(
        default_factory=TokenUsage, description="Sum of token usage across all calls"
    )
    calls: list[PredictCallDetail] = Field(description="Per-call duration and usage")


class ToolCall(BaseModel):
    """A single tool call made from sandbox code (excluding predict)."""

    name: str = Field(description="Tool function name")
    args: list[Any] = Field(default_factory=list, description="Positional arguments")
    kwargs: dict[str, Any] = Field(default_factory=dict, description="Keyword arguments")
    result: Any = Field(default=None, description="Return value from the tool")
    error: str | None = Field(default=None, description="Error message if the call failed")
    duration_ms: int = Field(description="Wall-clock duration in milliseconds")


class IterationStep(BaseModel):
    """One iteration of the RLM code-generation loop."""

    iteration: int = Field(description="1-indexed iteration number")
    reasoning: str = Field(description="LM reasoning for this iteration")
    code: str = Field(description="Python code generated by the LM")
    output: str = Field(
        description="Sandbox output as shown to the model (truncated to 5K chars)"
    )
    untruncated_output: str = Field(description="Full sandbox output before prompt truncation")
    error: bool = Field(default=False, description="True if code execution raised an error")
    duration_ms: int = Field(description="Wall-clock duration of this iteration")
    tool_calls: list[ToolCall] = Field(
        default_factory=list,
        description="Tool calls made during this iteration (excluding predict)",
    )
    predict_calls: list[PredictCallGroup] = Field(
        default_factory=list,
        description="predict() subcalls made during this iteration, grouped by signature",
    )


class LMUsage(BaseModel):
    """Token usage split by main LM and sub-LM."""

    main: TokenUsage = Field(default_factory=TokenUsage, description="Main LM token usage")
    sub: TokenUsage = Field(default_factory=TokenUsage, description="Sub-LM token usage")


class RunTrace(BaseModel):
    """Structured trace of a PredictRLM run.

    Attached to the returned ``dspy.Prediction`` as ``prediction.trace``.

    .. warning:: This schema is experimental and may change in future versions.
    """

    status: Literal["completed", "max_iterations", "error"] = Field(
        description=(
            "'completed' if SUBMIT was called, "
            "'max_iterations' if extract fallback was used, "
            "'error' if the run failed"
        )
    )
    model: str = Field(description="Main LM model identifier")
    sub_model: str | None = Field(
        default=None, description="Sub-LM model identifier, if different from main LM"
    )
    iterations: int = Field(description="Total iterations executed")
    max_iterations: int = Field(description="Maximum iterations allowed")
    duration_ms: int = Field(description="Total wall-clock duration in milliseconds")
    usage: LMUsage = Field(
        default_factory=LMUsage, description="Token usage split by main and sub LM"
    )
    steps: list[IterationStep] = Field(
        default_factory=list, description="Per-iteration execution steps"
    )

    def __repr__(self) -> str:
        return self.to_exportable_json()

    def to_exportable_json(self, path: str | Path | None = None, indent: int = 2) -> str:
        """Serialize the trace to a compact JSON string suitable for export.

        Unlike ``model_dump()``, which preserves the full in-memory data
        (including raw base64 image payloads from ``dspy.Image`` inputs),
        this method replaces large binary data with compact summaries
        before serializing — matching the format used by
        ``dspy.Image.__repr__``.

        For example, a 200KB base64 PNG becomes::

            "data:image/png;base64,<IMAGE_BASE_64_ENCODED(273648)>"

        Use ``model_dump()`` when you need the full data (e.g. to
        programmatically access image payloads). Use this method when
        writing traces to disk or sending them over the network.

        Args:
            path: If provided, write the JSON to this file and return the
                  JSON string. If ``None``, just return the JSON string.
            indent: JSON indentation level. Defaults to 2.

        Returns:
            The compact JSON string.
        """
        data = _sanitize_for_trace(self.model_dump())
        output = json.dumps(data, indent=indent, default=str)
        if path is not None:
            Path(path).write_text(output)
        return output


# ---------------------------------------------------------------------------
# Helpers for instrumentation
# ---------------------------------------------------------------------------

_BASE64_DATA_RE = re.compile(r"data:image/([^;]+);base64,([A-Za-z0-9+/=]+)")


def _sanitize_for_trace(value: Any) -> Any:
    """Replace base64 data URIs with length summaries.

    Replaces ``data:image/{type};base64,{payload}`` with
    ``data:image/{type};base64,<IMAGE_BASE_64_ENCODED({len})>``,
    matching the format used by ``dspy.Image.__repr__``.
    """
    if isinstance(value, str):
        if ";base64," not in value:
            return value

        def _replace_base64(m: re.Match) -> str:
            return f"data:image/{m.group(1)};base64,<IMAGE_BASE_64_ENCODED({len(m.group(2))})>"

        return _BASE64_DATA_RE.sub(_replace_base64, value)
    if isinstance(value, dict):
        return {k: _sanitize_for_trace(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_sanitize_for_trace(item) for item in value]
    return value


# Internal record for a single predict() call before aggregation.
class _RawPredictCall:
    __slots__ = (
        "signature",
        "instructions",
        "model",
        "duration_ms",
        "usage",
        "input",
        "output",
        "error",
    )

    def __init__(
        self,
        signature: str,
        instructions: str | None,
        model: str,
        duration_ms: int,
        usage: TokenUsage,
        input: dict[str, Any],
        output: dict[str, Any],
        error: str | None = None,
    ):
        self.signature = signature
        self.instructions = instructions
        self.model = model
        self.duration_ms = duration_ms
        self.usage = usage
        self.input = input
        self.output = output
        self.error = error


# ContextVar holding raw predict() calls for the current iteration.
# Cleared before each iteration, drained and aggregated after.
_predict_calls: ContextVar[list[_RawPredictCall]] = ContextVar("_predict_calls")


def record_predict_call(call: _RawPredictCall) -> None:
    """Append a predict() subcall to the current iteration's collector."""
    try:
        calls = _predict_calls.get()
    except LookupError:
        return  # No active trace collection — silently skip
    calls.append(call)


def drain_predict_calls() -> list[PredictCallGroup]:
    """Return aggregated predict() subcalls collected for this iteration.

    Calls sharing the same (signature, instructions, model) are grouped into
    a single PredictCallGroup with per-call details preserved.
    """
    try:
        calls = _predict_calls.get()
    except LookupError:
        return []

    groups: dict[tuple[str, str | None, str], list[_RawPredictCall]] = {}
    for call in calls:
        key = (call.signature, call.instructions, call.model)
        groups.setdefault(key, []).append(call)

    result: list[PredictCallGroup] = []
    for (sig, instr, model), group_calls in groups.items():
        total_usage = TokenUsage()
        for c in group_calls:
            total_usage += c.usage
        result.append(
            PredictCallGroup(
                signature=sig,
                instructions=instr,
                model=model,
                total_usage=total_usage,
                calls=[
                    PredictCallDetail(
                        duration_ms=c.duration_ms,
                        usage=c.usage,
                        input=c.input,
                        output=c.output,
                        error=c.error,
                    )
                    for c in group_calls
                ],
            )
        )

    calls.clear()
    return result


def init_predict_call_collector() -> Token:
    """Initialize (or reset) the predict call collector for a new run."""
    return _predict_calls.set([])


def reset_predict_call_collector(token: Token) -> None:
    """Restore the previous predict call collector."""
    _predict_calls.reset(token)


# ContextVar holding tool calls for the current iteration.
_tool_calls: ContextVar[list[ToolCall]] = ContextVar("_tool_calls")


def record_tool_call(call: ToolCall) -> None:
    """Append a tool call to the current iteration's collector."""
    try:
        calls = _tool_calls.get()
    except LookupError:
        return
    calls.append(call)


def drain_tool_calls() -> list[ToolCall]:
    """Return and clear all tool calls collected for this iteration."""
    try:
        calls = _tool_calls.get()
    except LookupError:
        return []
    result = list(calls)
    calls.clear()
    return result


def init_tool_call_collector() -> Token:
    """Initialize (or reset) the tool call collector for a new run."""
    return _tool_calls.set([])


def reset_tool_call_collector(token: Token) -> None:
    """Restore the previous tool call collector."""
    _tool_calls.reset(token)


def snapshot_lm_history_len(lm: Any) -> int:
    """Return the current length of an LM's history list."""
    history = getattr(lm, "history", None)
    return len(history) if history is not None else 0


def usage_since(lm: Any, since: int) -> TokenUsage:
    """Sum token usage from LM history entries added after index ``since``.

    Cache hits are detected and excluded from ``input_tokens`` / ``output_tokens``
    / ``cost`` — DSPy's ``Cache.get()`` zeros ``response.usage`` on a hit but
    leaves ``response._hidden_params["response_cost"]`` intact, so a naïve sum
    would mis-report phantom cost with no matching tokens. The hit count is
    surfaced via ``TokenUsage.cache_hits``.
    """
    history = getattr(lm, "history", None)
    if not history or len(history) <= since:
        return TokenUsage()
    input_tok = 0
    output_tok = 0
    cost = 0.0
    cache_hits = 0
    for entry in history[since:]:
        usage = entry.get("usage", {}) or {}
        entry_cost = entry.get("cost", 0) or 0
        if _is_cache_hit(entry, usage, entry_cost):
            cache_hits += 1
            continue
        input_tok += usage.get("prompt_tokens", 0) or 0
        output_tok += usage.get("completion_tokens", 0) or 0
        cost += entry_cost
    return TokenUsage(
        input_tokens=input_tok,
        output_tokens=output_tok,
        cost=cost,
        cache_hits=cache_hits,
    )


def _is_cache_hit(entry: dict, usage: dict, cost: float) -> bool:
    """Return True if ``entry`` is a DSPy cache-hit artifact.

    Two signals, checked in order of reliability:
      1. ``response.cache_hit`` flag set by ``dspy.clients.cache.Cache.get``.
      2. Empty usage dict paired with non-zero cost — a real LM call always
         populates prompt_tokens / completion_tokens, so this combination is
         unambiguous even when the response object is missing.
    """
    response = entry.get("response")
    if response is not None and getattr(response, "cache_hit", False):
        return True
    if not usage and cost:
        return True
    return False


def ms_since(start: float) -> int:
    """Milliseconds elapsed since ``start`` (from ``time.perf_counter()``)."""
    return int((time.perf_counter() - start) * 1000)


def extract_trace_from_exc(exc: BaseException | None) -> Any:
    """Walk the exception chain looking for an attached RunTrace.

    ``PredictRLM`` attaches ``exc.trace`` to any exception that flows
    through its error handler. When ``asyncio.wait_for`` times out, the
    inner ``CancelledError`` carries the trace but the outer
    ``TimeoutError`` raised by ``wait_for`` does not — the trace lives
    on the outer exception's ``__context__`` (or ``__cause__`` if
    something in between used ``raise X from Y``).

    This helper walks ``exc`` → ``__cause__`` → ``__context__`` until
    it finds a ``.trace`` attribute or runs out of links, so callers
    can treat all error paths uniformly without caring where in the
    chain the trace was attached. Cycles (pathological but possible)
    are guarded via an id-set.
    """
    if exc is None:
        return None
    seen: set[int] = set()
    cur: BaseException | None = exc
    while cur is not None and id(cur) not in seen:
        seen.add(id(cur))
        tr = getattr(cur, "trace", None)
        if tr is not None:
            return tr
        cur = cur.__cause__ or cur.__context__
    return None
